### ISSUE TITLE
[bug] EDUPAGE unexpected login error: list index out of range

### ISSUE THREAD

**Issue by mgrfilipmarek** [rine77/homeassistantedupage#70]
**Describe the bug**
login error and after that next issues with getStudents and unidecode.
(I guess) this issue occurs in this scenario:
- HA with edupage integration is down for some time
- login session is time-outed
- login method throws "list index out of range"
- get_students() throws NotLoggedInException
- unidecode throws error because student_name = unknown

This error originated from a custom integration.
Logger: custom_components.homeassistantedupage.homeassistant_edupage
Source: custom_components/homeassistantedupage/homeassistant_edupage.py:45
integration: homeassistantedupage (documentation, issues)
First occurred: 8:07:46 AM (9 occurrences)
Last logged: 8:25:10 AM
EDUPAGE unexpected login error: list index out of range

This error originated from a custom integration.
Logger: custom_components.homeassistant_edupage
Source: custom_components/homeassistantedupage/__init__.py:133
integration: homeassistant_edupage
First occurred: 8:11:03 AM (6 occurrences)
Last logged: 8:25:12 AM
INIT Failed to fetch timetable: EDUPAGE error updating get_students() data from API:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:365
integration: Sensor (documentation, issues)
First occurred: 8:22:04 AM (2 occurrences)
Last logged: 8:25:12 AM
Error while setting up homeassistantedupage platform for sensor
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/workspaces/core/config/custom_components/homeassistantedupage/sensor.py", line 45, in async_setup_entry
    notify = EduPageNotificationSensor(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/config/custom_components/homeassistantedupage/sensor.py", line 121, in __init__
    self._student_name = unidecode(student_name).replace(' ', '_').lower()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/unidecode/__init__.py", line 60, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
                 ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

**Screenshots**
![image](https://github.com/user-attachments/assets/d449007e-c3b9-4615-ab65-71274c0e5037)

**Comment by bbirnbach** [comment]
> * HA with edupage integration is down for some time

Without taking a deeper look I'm pretty sure that this is a problem because of the saved session (which is needed to not handle 2FA).  I think the session is timed out and needs a re-login.  For users without 2FA it could be a solution to catch that specific error and continue with "normal" login. 
Sounds like the whole login process has to be refactored :/

**Comment by rine77** [comment]
PR #96 introduces the right general approach for this issue: session-only runtime authentication, session-expiration handling, and a reauthentication flow.

However, the exact failure reported here is not handled reliably yet. If `Login.reload_data()` raises `IndexError: list index out of range`, it is currently converted into a generic `UpdateFailed`, so Home Assistant does not recognize it as an authentication failure and does not start reauthentication.

There is also a case where `EdupageSessionExpired` is raised inside `login()` but then caught by the broad `except Exception` handler and converted into `UpdateFailed`.

Ideally, an invalid or expired session should result in Home Assistant's standard `ConfigEntryAuthFailed`, while temporary connection errors should remain regular update failures.

A regression test should reproduce the original scenario:

```text
Login.reload_data() raises IndexError
```

and verify that:

* reauthentication is initiated;
* calendar and sensor platforms are not initialized with incomplete coordinator data;
* no subsequent `unidecode(None)` error occurs.

I will keep this issue open and link it to PR #96. Once this failure path is handled and covered by a test, the issue can be closed by that PR.
